services:

  loki:
    image: grafana/loki:3.7.4
    command: -config.file=/etc/loki/config.yml
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - log-collection:/loki

volumes:
  log-collection:
