spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordermesh-retry
    username: user
    password: password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


server:
  port: 9100
