spring:
  datasource:
    url: jdbc:postgresql://192.168.219.105:5432/ordermesh-retry
    username: user
    password: password

logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


server:
  port: 9100
