-- Flyway Migration

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    point_balance INT NOT NULL DEFAULT 0,
    last_login_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_login_id UNIQUE (login_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_name ON users (name);

COMMENT ON TABLE users IS '사용자 계정의 기본 식별 정보와 서비스 상태를 관리하는 기준 테이블';
COMMENT ON COLUMN users.id IS '사용자 PK';
COMMENT ON COLUMN users.login_id IS '로그인에 사용하는 계정 ID, 서비스 내부 고유값으로 관리';
COMMENT ON COLUMN users.name IS '사용자 이름, 조회 빈도가 있을 수 있어 인덱스 추가';
COMMENT ON COLUMN users.email IS '이메일 주소, 사용자 식별 및 알림 채널로 활용 가능';
COMMENT ON COLUMN users.phone IS 'SMS/알림톡 등 발송 대상 번호';
COMMENT ON COLUMN users.status IS '사용자 상태값, 예: ACTIVE, INACTIVE, SUSPENDED';
COMMENT ON COLUMN users.point_balance IS '현재 누적 포인트 잔액';
COMMENT ON COLUMN users.last_login_at IS '마지막 로그인 일시, 휴면 사용자 판별이나 최근 접속 분석에 활용 가능';
COMMENT ON COLUMN users.deleted_at IS '소프트 삭제 시점, 실제 row 삭제 없이 삭제 여부를 표현 가능';
COMMENT ON COLUMN users.created_at IS '사용자 생성 일시';
COMMENT ON COLUMN users.updated_at IS '사용자 정보 최종 수정 일시';

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(150) NOT NULL,
    product_code VARCHAR(50) NOT NULL,
    price DECIMAL(15,2) NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'SALE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_products_code UNIQUE (product_code)
);

CREATE INDEX idx_products_status ON products (status);
CREATE INDEX idx_products_name ON products (product_name);

COMMENT ON TABLE products IS '상품 기본 정보와 판매 가능 상태를 관리하는 기준 테이블';
COMMENT ON COLUMN products.id IS '상품 PK';
COMMENT ON COLUMN products.product_name IS '상품명, 상품명 조회를 고려해 인덱스 추가';
COMMENT ON COLUMN products.product_code IS '상품 식별 코드, 서비스 내부 고유값으로 관리';
COMMENT ON COLUMN products.price IS '현재 판매 가격';
COMMENT ON COLUMN products.stock_quantity IS '현재 재고 수량';
COMMENT ON COLUMN products.status IS '상품 상태값, 삭제 대신 상태로 관리하며 예: SALE, STOP, SOLD_OUT';
COMMENT ON COLUMN products.created_at IS '상품 등록 일시';
COMMENT ON COLUMN products.updated_at IS '상품 정보 최종 수정 일시';

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    order_status VARCHAR(30) NOT NULL,
    order_status_changed_at TIMESTAMP NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    ordered_at TIMESTAMP NOT NULL,
    cancelled_at TIMESTAMP NULL,
    failure_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_orders_order_no UNIQUE (order_no),
    CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_order_status ON orders (order_status);
CREATE INDEX idx_orders_ordered_at ON orders (ordered_at);

COMMENT ON TABLE orders IS '주문 기본 정보와 주문 상태 흐름을 관리하는 기준 테이블';
COMMENT ON COLUMN orders.id IS '주문 PK';
COMMENT ON COLUMN orders.order_no IS '주문 번호, 서비스 내부 고유값으로 관리';
COMMENT ON COLUMN orders.user_id IS '주문한 사용자 ID';
COMMENT ON COLUMN orders.order_status IS '주문 상태값, 예: CREATED, CONFIRMED, FAILED, CANCELLED';
COMMENT ON COLUMN orders.order_status_changed_at IS '주문 상태가 마지막으로 변경된 일시';
COMMENT ON COLUMN orders.total_amount IS '주문 총 금액';
COMMENT ON COLUMN orders.ordered_at IS '주문 생성 시각';
COMMENT ON COLUMN orders.cancelled_at IS '주문 취소 시각';
COMMENT ON COLUMN orders.failure_reason IS '주문 실패 또는 취소 사유';
COMMENT ON COLUMN orders.created_at IS '주문 데이터 생성 일시';
COMMENT ON COLUMN orders.updated_at IS '주문 데이터 최종 수정 일시';

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL,
    line_amount DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_items_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);

COMMENT ON TABLE order_items IS '주문에 포함된 상품 상세 내역과 주문 시점 스냅샷 정보를 저장하는 테이블';
COMMENT ON COLUMN order_items.id IS '주문 상품 항목 PK';
COMMENT ON COLUMN order_items.order_id IS '주문 ID';
COMMENT ON COLUMN order_items.product_id IS '상품 ID';
COMMENT ON COLUMN order_items.product_name_snapshot IS '주문 시점의 상품명 스냅샷';
COMMENT ON COLUMN order_items.quantity IS '주문 수량';
COMMENT ON COLUMN order_items.unit_price IS '주문 시점의 개별 상품 단가';
COMMENT ON COLUMN order_items.line_amount IS '주문 항목 총 금액, 일반적으로 quantity * unit_price';
COMMENT ON COLUMN order_items.created_at IS '주문 상품 항목 생성 일시';

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    payment_no VARCHAR(50) NOT NULL,
    method VARCHAR(30) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    approved_at TIMESTAMP NULL,
    failed_at TIMESTAMP NULL,
    failure_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_payments_payment_no UNIQUE (payment_no),
    CONSTRAINT fk_payments_order_id FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_status ON payments (payment_status);

COMMENT ON TABLE payments IS '주문 결제 정보와 결제 처리 상태를 관리하는 테이블';
COMMENT ON COLUMN payments.id IS '결제 PK';
COMMENT ON COLUMN payments.order_id IS '연관된 주문 ID, 한 주문에 여러 결제 시도가 가능하도록 unique 제약 제거';
COMMENT ON COLUMN payments.payment_no IS '결제 번호, 서비스 내부 고유값으로 관리';
COMMENT ON COLUMN payments.method IS '결제 수단, 예: CARD, BANK_TRANSFER, VBANK';
COMMENT ON COLUMN payments.amount IS '결제 금액';
COMMENT ON COLUMN payments.payment_status IS '결제 상태값, 예: READY, PAID, FAILED, CANCELLED';
COMMENT ON COLUMN payments.approved_at IS '결제 승인 시각';
COMMENT ON COLUMN payments.failed_at IS '결제 실패 시각';
COMMENT ON COLUMN payments.failure_reason IS '결제 실패 사유';
COMMENT ON COLUMN payments.created_at IS '결제 데이터 생성 일시';
COMMENT ON COLUMN payments.updated_at IS '결제 데이터 최종 수정 일시';

CREATE TABLE point_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    point_type VARCHAR(30) NOT NULL,
    point_amount INT NOT NULL,
    balance_after INT NOT NULL,
    process_status VARCHAR(30) NOT NULL,
    event_id VARCHAR(100) NOT NULL,
    processed_at TIMESTAMP NULL,
    failed_at TIMESTAMP NULL,
    failure_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_point_histories_event_id UNIQUE (event_id),
    CONSTRAINT fk_point_histories_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_point_histories_order_id FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_point_histories_user_id ON point_histories (user_id);
CREATE INDEX idx_point_histories_order_id ON point_histories (order_id);
CREATE INDEX idx_point_histories_process_status ON point_histories (process_status);

COMMENT ON TABLE point_histories IS '포인트 적립 및 차감 처리 이력과 처리 결과를 저장하는 테이블';
COMMENT ON COLUMN point_histories.id IS '포인트 이력 PK';
COMMENT ON COLUMN point_histories.user_id IS '포인트를 적립 또는 차감한 사용자 ID';
COMMENT ON COLUMN point_histories.order_id IS '포인트 적립 기준이 된 주문 ID';
COMMENT ON COLUMN point_histories.point_type IS '포인트 유형, 예: EARN, CANCEL, EXPIRE';
COMMENT ON COLUMN point_histories.point_amount IS '처리된 포인트 증감 수치';
COMMENT ON COLUMN point_histories.balance_after IS '포인트 처리 후 사용자 잔액';
COMMENT ON COLUMN point_histories.process_status IS '포인트 처리 상태값, 예: READY, SUCCESS, FAILED';
COMMENT ON COLUMN point_histories.event_id IS '포인트 적립 처리와 연결된 이벤트 식별자, 중복 처리 방지를 위해 유니크하게 관리';
COMMENT ON COLUMN point_histories.processed_at IS '포인트 처리 완료 시각';
COMMENT ON COLUMN point_histories.failed_at IS '포인트 처리 실패 시각';
COMMENT ON COLUMN point_histories.failure_reason IS '포인트 처리 실패 사유';
COMMENT ON COLUMN point_histories.created_at IS '포인트 이력 생성 일시';
COMMENT ON COLUMN point_histories.updated_at IS '포인트 이력 최종 수정 일시';

CREATE TABLE event_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version VARCHAR(20) NOT NULL,
    routing_key VARCHAR(100) NOT NULL,
    exchange_name VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    publish_status VARCHAR(30) NOT NULL,
    publish_attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP NULL,
    last_attempted_at TIMESTAMP NULL,
    last_published_at TIMESTAMP NULL,
    published_at TIMESTAMP NULL,
    failure_reason VARCHAR(255) NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_event_logs_event_id UNIQUE (event_id)
);

CREATE INDEX idx_event_logs_event_type ON event_logs (event_type);
CREATE INDEX idx_event_logs_publish_status ON event_logs (publish_status);
CREATE INDEX idx_event_logs_occurred_at ON event_logs (occurred_at);
CREATE INDEX idx_event_logs_publish_status_occurred_at ON event_logs (publish_status, occurred_at);
CREATE INDEX idx_event_logs_publish_status_next_retry_at_occurred_at ON event_logs (publish_status, next_retry_at, occurred_at);

COMMENT ON TABLE event_logs IS '이벤트 발행 이력과 Outbox 역할을 함께 수행하는 테이블';
COMMENT ON COLUMN event_logs.id IS '이벤트 로그 PK';
COMMENT ON COLUMN event_logs.event_id IS '이벤트 고유 식별자, 중복 발행 방지를 위해 유니크하게 관리';
COMMENT ON COLUMN event_logs.event_type IS '이벤트 타입, 예: ORDER_CREATED, PAYMENT_COMPLETED';
COMMENT ON COLUMN event_logs.event_version IS '이벤트 스키마 버전';
COMMENT ON COLUMN event_logs.routing_key IS 'RabbitMQ 발행 시 사용하는 라우팅 키';
COMMENT ON COLUMN event_logs.exchange_name IS 'RabbitMQ 발행 대상 exchange 이름';
COMMENT ON COLUMN event_logs.payload IS '발행할 이벤트 본문 데이터';
COMMENT ON COLUMN event_logs.publish_status IS '발행 상태값, 예: READY, PUBLISHED, FAILED, RETRYING';
COMMENT ON COLUMN event_logs.publish_attempt_count IS '이벤트 발행 시도 횟수';
COMMENT ON COLUMN event_logs.next_retry_at IS '다음 재발행 예정 시각';
COMMENT ON COLUMN event_logs.last_attempted_at IS '마지막 발행 시도 시각';
COMMENT ON COLUMN event_logs.last_published_at IS '마지막으로 발행 성공 처리한 시각';
COMMENT ON COLUMN event_logs.published_at IS '최초 발행 성공 시각';
COMMENT ON COLUMN event_logs.failure_reason IS '발행 실패 사유';
COMMENT ON COLUMN event_logs.occurred_at IS '도메인 이벤트 실제 발생 시각';
COMMENT ON COLUMN event_logs.created_at IS '이벤트 로그 생성 일시';
COMMENT ON COLUMN event_logs.updated_at IS '이벤트 로그 최종 수정 일시';

CREATE TABLE failed_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(100) NOT NULL,
    consumer_name VARCHAR(100) NOT NULL,
    queue_name VARCHAR(100) NOT NULL,
    exchange_name VARCHAR(100) NOT NULL,
    routing_key VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    failure_type VARCHAR(50) NOT NULL,
    failure_reason TEXT NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry_count INT NOT NULL DEFAULT 3,
    last_failed_at TIMESTAMP NOT NULL,
    dlq_stored_yn CHAR(1) NOT NULL DEFAULT 'N',
    reprocess_status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    reprocessed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_failed_messages_consumer_event UNIQUE (consumer_name, event_id)
);

CREATE INDEX idx_failed_messages_reprocess_status ON failed_messages (reprocess_status);
CREATE INDEX idx_failed_messages_last_failed_at ON failed_messages (last_failed_at);
CREATE INDEX idx_failed_messages_failure_type ON failed_messages (failure_type);

COMMENT ON TABLE failed_messages IS 'Consumer 처리 실패 메시지와 재처리 상태를 관리하는 테이블';
COMMENT ON COLUMN failed_messages.id IS '실패 메시지 이력 PK';
COMMENT ON COLUMN failed_messages.event_id IS '실패한 이벤트 식별자';
COMMENT ON COLUMN failed_messages.consumer_name IS '실패를 발생시킨 Consumer 이름';
COMMENT ON COLUMN failed_messages.queue_name IS '메시지를 수신한 큐 이름';
COMMENT ON COLUMN failed_messages.exchange_name IS '메시지가 라우팅된 exchange 이름';
COMMENT ON COLUMN failed_messages.routing_key IS '메시지 라우팅에 사용된 routing key';
COMMENT ON COLUMN failed_messages.payload IS '실패한 원본 메시지 payload';
COMMENT ON COLUMN failed_messages.failure_type IS '실패 유형, 예: BUSINESS, SYSTEM, TIMEOUT';
COMMENT ON COLUMN failed_messages.failure_reason IS '실패 상세 사유';
COMMENT ON COLUMN failed_messages.retry_count IS '현재까지 수행한 재시도 횟수';
COMMENT ON COLUMN failed_messages.max_retry_count IS '허용된 최대 재시도 횟수';
COMMENT ON COLUMN failed_messages.last_failed_at IS '마지막 실패 발생 시각';
COMMENT ON COLUMN failed_messages.dlq_stored_yn IS 'DLQ 적재 여부, Y 또는 N';
COMMENT ON COLUMN failed_messages.reprocess_status IS '재처리 상태값, 예: WAITING, PROCESSING, SUCCESS, FAILED';
COMMENT ON COLUMN failed_messages.reprocessed_at IS '재처리 완료 시각';
COMMENT ON COLUMN failed_messages.created_at IS '실패 메시지 이력 생성 일시';
COMMENT ON COLUMN failed_messages.updated_at IS '실패 메시지 이력 최종 수정 일시';

CREATE TABLE message_process_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id VARCHAR(100) NOT NULL,
    event_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    consumer_name VARCHAR(100) NOT NULL,
    queue_name VARCHAR(100) NOT NULL,
    process_status VARCHAR(30) NOT NULL,
    received_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP NULL,
    acked_at TIMESTAMP NULL,
    duplicate_yn CHAR(1) NOT NULL DEFAULT 'N',
    retry_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(255) NULL,
    trace_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_message_process_logs_status ON message_process_logs (process_status);
CREATE INDEX idx_message_process_logs_received_at ON message_process_logs (received_at);
CREATE INDEX idx_message_process_logs_trace_id ON message_process_logs (trace_id);
CREATE INDEX idx_message_process_logs_event_type ON message_process_logs (event_type);

COMMENT ON TABLE message_process_logs IS 'Consumer의 메시지 처리 성공, 실패, 중복, 재시도 이력을 기록하는 테이블';
COMMENT ON COLUMN message_process_logs.id IS '메시지 처리 로그 PK';
COMMENT ON COLUMN message_process_logs.message_id IS '수신한 메시지 식별자';
COMMENT ON COLUMN message_process_logs.event_id IS '처리 대상 이벤트 식별자';
COMMENT ON COLUMN message_process_logs.event_type IS '이벤트 타입';
COMMENT ON COLUMN message_process_logs.consumer_name IS '메시지를 처리한 Consumer 이름';
COMMENT ON COLUMN message_process_logs.queue_name IS '메시지를 수신한 큐 이름';
COMMENT ON COLUMN message_process_logs.process_status IS '처리 상태값, 예: RECEIVED, PROCESSING, SUCCESS, FAILED, DUPLICATE, RETRY, DLQ';
COMMENT ON COLUMN message_process_logs.received_at IS '메시지를 수신한 시각';
COMMENT ON COLUMN message_process_logs.processed_at IS '메시지 처리 완료 시각';
COMMENT ON COLUMN message_process_logs.acked_at IS '브로커에 ack를 보낸 시각';
COMMENT ON COLUMN message_process_logs.duplicate_yn IS '중복 메시지 여부, Y 또는 N';
COMMENT ON COLUMN message_process_logs.retry_count IS '해당 메시지 처리의 재시도 횟수';
COMMENT ON COLUMN message_process_logs.error_message IS '처리 실패 또는 예외 발생 시 에러 메시지';
COMMENT ON COLUMN message_process_logs.trace_id IS '분산 추적을 위한 trace 식별자';
COMMENT ON COLUMN message_process_logs.created_at IS '메시지 처리 로그 생성 일시';
